import "server-only";

import { publicEnv } from "@/lib/config/env";

/**
 * Layer Flow's transactional-email visual system.
 *
 * Every builder in lib/email/templates.ts composes its HTML through
 * `renderEmailHtml` below, so every email -- welcome, receipt, payment
 * confirmation, cancellation -- shares one header, hero, card, button and
 * footer language rather than each template inventing its own markup.
 *
 * Table-based and inline-styled throughout: Outlook's Word rendering engine
 * ignores flexbox/grid and most of a <style> block, so the layout has to
 * survive on tables + inline styles alone. The <style> block that does exist
 * is progressive enhancement (mobile padding, base resets) -- never
 * load-bearing.
 *
 * Icons are hosted PNGs (public/icons/email/, generated by
 * scripts/generate-email-icons.mjs from a small line-icon set) inside a soft
 * circular badge -- not inline <svg>. An earlier version used inline SVG,
 * which turned out not to render in Gmail (confirmed against a real Gmail
 * delivery, not just Outlook, which was the only gap originally assumed);
 * only Apple Mail reliably renders inline SVG among major clients. Same
 * approach as the header logo below: a plain `<img>` with a real URL, served
 * by the app itself, renders everywhere.
 */

export const EMAIL_COLORS = {
  // A blend of the brief's original forest green (#164F3B) and the app's own
  // --primary token (#11883D, see scripts/contrast.mjs): richer than the
  // brighter app green, warmer than the original's darker, more muted tone.
  primary: "#146C3C",
  deepGreen: "#0F5E36",
  medium: "#327258",
  pale: "#EEF6F1",
  light: "#DCEFDC",
  muted: "#496A62",
  bg: "#F3F6F4",
  white: "#FFFFFF",
  border: "#E1E8E3",
  text: "#12261D",
} as const;

const FONT_STACK =
  "-apple-system,BlinkMacSystemFont,'Inter','Segoe UI',Helvetica,Arial,sans-serif";

/** Icon names with a generated PNG under public/icons/email/ -- keep in sync with scripts/generate-email-icons.mjs's ICONS map. */
type EmailIconName =
  | "egg"
  | "check-circle"
  | "alert-circle"
  | "alert-triangle"
  | "refresh"
  | "box"
  | "card"
  | "calendar"
  | "receipt"
  | "note"
  | "clipboard"
  | "chart"
  | "users"
  | "mail"
  | "chat"
  | "log-out"
  | "leaf";

type EmailIconTone = "primary" | "medium";

/** `size` in px, at which the pre-rasterized 96px PNG is displayed. */
function icon(
  name: EmailIconName,
  { size = 20, tone = "primary" }: { size?: number; tone?: EmailIconTone } = {}
): string {
  const src = `${publicEnv.appUrl}/icons/email/${name}-${tone}.png`;
  // margin:0 auto alongside display:block: a block-level image ignores its
  // container's align="center" (that only centers inline content), which is
  // why the hero badge's icon was leaning left in its circle -- this is the
  // standard cross-client fix (Outlook's Word engine, Gmail, Apple Mail all
  // respect it).
  return `<img src="${src}" width="${size}" height="${size}" alt="" style="display:block;margin:0 auto;border:0;width:${size}px;height:${size}px;" />`;
}

export interface EmailInfoRow {
  icon?: EmailIconName;
  label: string;
  value: string;
}

export interface EmailFeature {
  icon: EmailIconName;
  title: string;
  text: string;
}

export interface EmailCta {
  label: string;
  href: string;
}

export interface RenderEmailOptions {
  /** Shown by the inbox list/preview pane; hidden in the rendered body. */
  preheader: string;
  eyebrow: string;
  headline: string;
  heroMessage?: string;
  heroIcon: EmailIconName;
  greetingName?: string;
  /** Paragraphs after the greeting, before any card. */
  intro?: string[];
  infoCard?: { title?: string; rows: EmailInfoRow[] };
  cta?: EmailCta;
  features?: EmailFeature[];
  /** A short note under the CTA -- a reactivate link, a "changed your mind?" line. */
  secondaryNote?: string;
  showSupport?: boolean;
  showBrandMessage?: boolean;
}

function escapeHtml(value: string): string {
  // Quotes too, not just &/</>: every current call site lands this as plain
  // text content, where quotes are harmless, but escaping them here as well
  // means a future caller can safely reuse this for an attribute value
  // (see escapeHtmlAttr below) without anyone having to remember a second,
  // stricter helper exists.
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * For a value placed inside a double-quoted HTML attribute (e.g. `href="..."`),
 * not text content. `escapeHtml` alone isn't enough there: it protects
 * against breaking out of the attribute, but a URL should also be
 * percent-encoded first so the two don't interact. `cta.href` is the one
 * attribute value in this file built from a template literal rather than a
 * static string -- every caller today only ever passes a server-built
 * `${publicEnv.appUrl}/...` URL, never raw user text, but nothing enforced
 * that, so this closes the gap defensively.
 */
function escapeHtmlAttr(url: string): string {
  return escapeHtml(encodeURI(url));
}

function paragraph(html: string, extraStyle = ""): string {
  return `<p style="margin:0 0 16px;font-size:15px;line-height:1.65;color:${EMAIL_COLORS.text};${extraStyle}">${html}</p>`;
}

function headerBlock(): string {
  // The real product mark (public/icons/layerflow-logo.png, also used by
  // components/nav/brand.tsx), not a text-only stand-in -- served by the app
  // itself, so unlike the icon set this is a real, hosted image and renders
  // in every client including Outlook (plain <img>, not SVG).
  const logoSrc = `${publicEnv.appUrl}/icons/layerflow-logo.png`;
  return `
  <tr>
    <td align="center" class="lf-px" style="padding:24px 40px;background:${EMAIL_COLORS.white};text-align:center;">
      <table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 auto;">
        <tr>
          <td width="28" height="28" valign="middle">
            <img src="${logoSrc}" width="28" height="28" alt="Layer Flow" style="display:block;border:0;width:28px;height:28px;" />
          </td>
          <td style="padding-left:9px;font-size:16px;font-weight:800;color:${EMAIL_COLORS.primary};">Layer Flow</td>
        </tr>
      </table>
    </td>
  </tr>`;
}

function heroBlock(opts: RenderEmailOptions): string {
  return `
  <tr>
    <td class="lf-px" style="background:${EMAIL_COLORS.pale};padding:40px 40px 36px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td valign="top" style="padding-right:20px;">
            <p style="margin:0 0 10px;font-size:12px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;color:${EMAIL_COLORS.medium};">${escapeHtml(opts.eyebrow)}</p>
            <h1 style="margin:0 0 12px;font-size:26px;line-height:1.3;font-weight:800;color:${EMAIL_COLORS.primary};">${escapeHtml(opts.headline)}</h1>
            ${opts.heroMessage ? `<p style="margin:0;font-size:15px;line-height:1.6;color:${EMAIL_COLORS.muted};">${escapeHtml(opts.heroMessage)}</p>` : ""}
          </td>
          <td valign="top" width="64" style="width:64px;">
            <table role="presentation" cellpadding="0" cellspacing="0">
              <tr>
                <td width="64" height="64" align="center" valign="middle" style="width:64px;height:64px;border-radius:32px;background:${EMAIL_COLORS.light};text-align:center;">${icon(opts.heroIcon, { size: 28, tone: "primary" })}</td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>`;
}

function infoCardBlock(card: NonNullable<RenderEmailOptions["infoCard"]>): string {
  const rows = card.rows
    .map(
      (row, i) => `
      <tr>
        <td style="padding:${i === 0 ? "0" : "10px"} 0 0;font-size:14px;color:${EMAIL_COLORS.muted};">${row.icon ? `<span style="display:inline-block;vertical-align:middle;margin-right:7px;line-height:0;">${icon(row.icon, { size: 15, tone: "medium" })}</span>` : ""}<span style="vertical-align:middle;">${escapeHtml(row.label)}</span></td>
        <td align="right" style="padding:${i === 0 ? "0" : "10px"} 0 0;font-size:14px;font-weight:700;color:${EMAIL_COLORS.text};">${escapeHtml(row.value)}</td>
      </tr>`
    )
    .join("");

  return `
  <tr>
    <td class="lf-px" style="padding:4px 40px 8px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${EMAIL_COLORS.pale};border-radius:12px;">
        <tr>
          <td style="padding:22px 24px;">
            ${card.title ? `<p style="margin:0 0 12px;font-size:13px;font-weight:700;color:${EMAIL_COLORS.primary};">${escapeHtml(card.title)}</p>` : ""}
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0">${rows}</table>
          </td>
        </tr>
      </table>
    </td>
  </tr>`;
}

function ctaBlock(cta: EmailCta, secondaryNote?: string): string {
  return `
  <tr>
    <td align="center" class="lf-px" style="padding:28px 40px 8px;">
      <table role="presentation" cellpadding="0" cellspacing="0">
        <tr>
          <td align="center" style="border-radius:999px;background:${EMAIL_COLORS.primary};">
            <a href="${escapeHtmlAttr(cta.href)}" style="display:inline-block;padding:14px 32px;font-size:15px;font-weight:700;color:${EMAIL_COLORS.white};text-decoration:none;border-radius:999px;">${escapeHtml(cta.label)} &rarr;</a>
          </td>
        </tr>
      </table>
      ${secondaryNote ? `<p style="margin:16px 0 0;font-size:13px;color:${EMAIL_COLORS.muted};">${escapeHtml(secondaryNote)}</p>` : ""}
    </td>
  </tr>`;
}

function featuresBlock(features: EmailFeature[]): string {
  const width = Math.floor(100 / features.length);
  const cells = features
    .map(
      (f, i) => `
      <td class="lf-feature-col" valign="top" width="${width}%" style="padding:0 8px ${i === features.length - 1 ? "0" : "8"}px;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${EMAIL_COLORS.white};border:1px solid ${EMAIL_COLORS.border};border-radius:10px;">
          <tr>
            <td style="padding:16px;">
              <div style="margin-bottom:10px;">${icon(f.icon, { size: 22, tone: "primary" })}</div>
              <p style="margin:0 0 4px;font-size:13px;font-weight:700;color:${EMAIL_COLORS.text};">${escapeHtml(f.title)}</p>
              <p style="margin:0;font-size:12.5px;line-height:1.5;color:${EMAIL_COLORS.muted};">${escapeHtml(f.text)}</p>
            </td>
          </tr>
        </table>
      </td>`
    )
    .join("");

  return `
  <tr>
    <td class="lf-px" style="padding:20px 32px 8px;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr class="lf-feature-row">${cells}</tr></table>
    </td>
  </tr>`;
}

function supportBlock(): string {
  return `
  <tr>
    <td align="center" class="lf-px" style="padding:24px 40px 0;text-align:center;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid ${EMAIL_COLORS.border};">
        <tr>
          <td align="center" style="padding:20px 0 0;font-size:13px;line-height:1.6;color:${EMAIL_COLORS.muted};text-align:center;">
            Need a hand? Reach out any time at
            <a href="mailto:support@layerflow.ph" style="color:${EMAIL_COLORS.medium};font-weight:600;text-decoration:none;">support@layerflow.ph</a>
            or visit the <a href="${publicEnv.appUrl}/support" style="color:${EMAIL_COLORS.medium};font-weight:600;text-decoration:none;">Help Center</a>.
          </td>
        </tr>
      </table>
    </td>
  </tr>`;
}

function brandMessageBlock(): string {
  return `
  <tr>
    <td align="center" class="lf-px" style="padding:18px 40px 32px;text-align:center;">
      <table role="presentation" cellpadding="0" cellspacing="0" style="margin:0 auto;">
        <tr>
          <td valign="top">${icon("leaf", { size: 15, tone: "medium" })}</td>
          <td valign="top" style="padding-left:6px;font-size:12.5px;line-height:1.6;color:${EMAIL_COLORS.muted};text-align:center;">
            Every farm on Layer Flow is one less spreadsheet and one clearer picture of what the flock actually earns.
          </td>
        </tr>
      </table>
    </td>
  </tr>`;
}

function footerBlock(): string {
  return `
  <tr>
    <td class="lf-px" align="center" style="background:${EMAIL_COLORS.deepGreen};padding:28px 40px;text-align:center;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
        <tr>
          <td align="center" style="font-size:11px;line-height:1.6;color:rgba(255,255,255,0.55);text-align:center;">
            &copy; ${new Date().getFullYear()} Layer Flow. All rights reserved.<br />
            <a href="${publicEnv.appUrl}/privacy" style="color:rgba(255,255,255,0.65);text-decoration:underline;">Privacy</a>
            &nbsp;&middot;&nbsp;
            <a href="${publicEnv.appUrl}/terms" style="color:rgba(255,255,255,0.65);text-decoration:underline;">Terms</a>
          </td>
        </tr>
      </table>
    </td>
  </tr>`;
}

export function renderEmailHtml(opts: RenderEmailOptions): string {
  const introHtml = (opts.intro ?? []).map((line) => paragraph(escapeHtml(line))).join("");
  const greeting = opts.greetingName
    ? paragraph(`Hi ${escapeHtml(opts.greetingName)},`, "font-weight:600;")
    : "";

  const body = `
${headerBlock()}
${heroBlock(opts)}
<tr>
  <td class="lf-px" style="padding:28px 40px 4px;">
    ${greeting}${introHtml}
  </td>
</tr>
${opts.infoCard ? infoCardBlock(opts.infoCard) : ""}
${opts.cta ? ctaBlock(opts.cta, opts.secondaryNote) : ""}
${opts.features ? featuresBlock(opts.features) : ""}
${opts.showSupport === false ? "" : supportBlock()}
${opts.showBrandMessage === false ? "" : brandMessageBlock()}
${footerBlock()}`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="color-scheme" content="light" />
<meta name="x-apple-disable-message-reformatting" />
<title>${escapeHtml(opts.headline)}</title>
<style>
  body,table,td,a { -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; }
  table,td { mso-table-lspace:0pt; mso-table-rspace:0pt; }
  img { -ms-interpolation-mode:bicubic; border:0; line-height:100%; outline:none; text-decoration:none; }
  body { margin:0; padding:0; width:100% !important; background:${EMAIL_COLORS.bg}; font-family:${FONT_STACK}; }
  @media screen and (max-width:600px) {
    .lf-container { width:100% !important; border-radius:0 !important; }
    .lf-outer { padding-left:6px !important; padding-right:6px !important; }
    .lf-px { padding-left:16px !important; padding-right:16px !important; }
    /* Feature cards (e.g. the welcome email's 3-up grid under the CTA
       button) stack one per row instead of squeezing three columns into a
       phone-width screen -- each <td> becomes a full-width block, which is
       what breaks a table out of its column layout. */
    .lf-feature-row { display:block !important; }
    .lf-feature-col {
      display:block !important;
      width:100% !important;
      padding:0 0 10px !important;
    }
    .lf-feature-col:last-child { padding-bottom:0 !important; }
  }
</style>
</head>
<body style="margin:0;padding:0;background:${EMAIL_COLORS.bg};">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all;">${escapeHtml(opts.preheader)}</div>
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${EMAIL_COLORS.bg};">
    <tr>
      <td align="center" class="lf-outer" style="padding:32px 16px;">
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" class="lf-container" style="width:600px;max-width:600px;background:${EMAIL_COLORS.white};border-radius:12px;overflow:hidden;border:1px solid ${EMAIL_COLORS.border};">${body}
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}
